[[plugins]]
repo = 'Shougo/dein.vim'

# ▼▼▼ ここから、Markdown 用 ▼▼▼
# ▲▲▲ ここまで、Markdown 用 ▲▲▲

# memo
[[plugins]]
repo = 'glidenote/memolist.vim'

#文字置換をリアルタイム反映
[[plugins]]
repo = 'markonm/traces.vim'

# 補完
[[plugins]]
repo = 'alvan/vim-closetag'

