[tools]
go = "latest"
node = "22"
typescript = "latest"
terraform = "latest"
python = "latest"

neovim = "stable"
lua = "5.1"
luarocks = "5.1"

peco = "latest"
ripgrep = "latest"
lazygit = "latest"
gh = "latest"
ghq = "latest"
oxker = "latest"

# Go tools
gopls = "latest"
golangci-lint = "latest"

"npm:@biomejs/biome" = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
