[tools]
go = "latest"
node = "20"
terraform = "latest"
ruby = "latest"
python = "latest"

neovim = "stable"

peco = "latest"
ripgrep = "latest"
lazygit = "latest"
gh = "latest"
ghq = "latest"

"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
